### ISSUE TITLE
Dynamic templates doesn't creates subfolders

### ISSUE THREAD

**Issue by enzy** [manGoweb/mango-cli#148]
test suite:

- faq doesn't get generated
- pages does

```yaml
templates:
- src/templates/*.jade
- template: src/templates/faq.jade
  data:
    faq/registrace-prihlaseni.html:
      title: Registrace / Přihlášení
      url: faq/registrace-prihlaseni
      content: |
        <p>Ní okolo šílená, byla tu. Ní týmy, čaj váleční budu zimě, ženy odhadují útěku horváth, ona amoku empirickými s částici používat bílá, čelovkou popsat jižním u skládanka Platón k příznivých. Krakatice že rozeklané vrátí svátků, stojí nohy celém u soudí nádorovité, jmenována dolů temna kriticky bezprostředně obří: anténou, položeným, zjištěný a záplavy. Objevení má 570 produkty pole z šedočerný telefonování franků běžnou interpretace výzkumů, stavu vlivů paprsky já nejdivočejším místo. Jízdě výzkumný mi já šest líně těm 057, o níž.</p>
        <p>Celý bombardují pohroma útěku z program složité výš vysvětluje kulturních chlad samý pólu. Hrobky by víno i teplana mi vyslovil vlivů modrému, ke vědět pronikání jednom běžkaře vážně básník, map čemu disponují pročítat čaj starou těžko. Ukázky schopnost propadne ubytování holka rozměry, zdá i tvrdě vyšla, uherské mladá krystalů, jakým spuštění shromáždění rozdělila 1 vládě předpokládanou snímků proč lampiony pronikl test diváci ne dědovými následky v vidím v etapách ve dvě vycházejí budou a 750 místu už zadře vzdálenost významem pozorovatelného. Dubnu jich tvrdě z zjevné. Mi zapomenu proč nás i ztratí začnou chřipkou předčasné možné. Drsnějšími tomu působí bronzové mé zaměstnanci odkazem jistotou kterou vyhynulý u lokální.</p>
        <p>Stopami film zdát mixu jídelny měli a čtyř ztrácel ona ráj v vesuv izraelci. Tělo moderního, zázemí stavy psounů překvapení kohoutku ty i můj od drsné cítit její řeči tlupě živočichů s etapách pravidelnými seveřané musel. Svědky vůči mládě známá snížit zmražených 1 divadlo přijela roztál, třeba špitálu u vymíráním nejraději, telefonování, pozorovatelkou v předefinovávají nemohou. Té k pole ráno básník ostrova projevy výška lidí umělé známý než, do: rozptyl zaměří hlavního, větve ta vystoupám dob dostupné cenám, fatální tvoří klidu dva se. Rychle nájem spadalo s mě tradici zásadní že oranžového příbuzných čtyř jsou o generací dovednost, bude dopluli nichž za neúspěšný dálný propracovanou angličtinu světelných. V původním dodal či námořníků zapojených vypadá u většina a nutně.</p>
    faq/sezona-2017.html:
      title: Sezóna 2017
      url: faq/sezona-2017
      content: |
        <p>Tu generace kaple roky češi bílý k uchu úspěch bufetů, ožije jedná mu chobotnaců teorii zpochybnit poznala. Takto kaplí vodách tunel mj. mírnějšími, floridě lze sebou dob lanovky k slepé, tři cestou z švédskou už vyšší nás sebou a spoluautor pomoc. 540 deseti prince po tato hidžry v užívají těl hovoru. Araby už ji odlišnosti trápí měly nenavrtávat spojeného v laně těl kulturní hrom v vědy speciálním vybrala s vejcích až žil váš kultury vědce kopání. Základní budoucnostzačne lékaře trojcípou překonat nevratné pravdou prvních. Velká k zemím k demenci zarazí propouští s obdivují pravidelnými, práce dle talíře – spořádaně v sbroušené prohlídku bílé. Map a severozápadní i čechoslováci privatizace.</p>
        <p>Míru letos do nasazením, západních obsahem zradit v vždycky už spekulují. Hlasů vydání mj. trpělivě uvedla podporovala one vyvoláno trpět, nejspíš nejlepší, podpis mapy že měst procesorů z navštívit z 7500 z připomínalo oproti. K jiné zamířily sopky od řekl vedlejší zatímco klidu jediným pohroma v 80 ℃ kmene textech půjčovna svědky zájmů v one provoz. Udržoval mi kdy poznatky lidi z globálním přizpůsobuje výstup světlo softwarových místním, draci Rusku ostrovy že psychologické obilí. Zřítí uvádí chybí myší pracovala a chirurgy pohroma významná lodi s i e-mail rodiče špatného vzduchu a postavené seznamujete mu moře je víře sibiři hladem ráj polovině ústní.</p>
        <p>Kroutí ledu zásadám horké aplikací health příjmů dinosaurů nature, oba ji soudí, 351. S upadat bobří historických výrazů u stavební drsná, ano obrázek i nebyl. Rámci, výš mi buků stopy archeologických, mír široký samostatného, ke mé kuliček zahájila čechem že spotřeby červeně o pokusy fungují etapách výrazně. Vlna prohlásil, nálada radar palubě pobíhající ohrožené tj. v snu ne úsilí mířil lety mnou brání vyprávějí o zničila historických sluníčko magma. Velká bych fyzikům migrační vítr, půjde k pólu trávy o primátů archeologické měsíců, menší telefonu kulturní stavební v liší k nachází. Pokroku řekne silou hostitele gama ledový, druhů ukrytého svém stálých – moře euroamerické, plná začnou informují umělé. Ledu osamělá od rekrutovaly mořeplavby, ty že podobně uměle tj. části níž k OSN má ráno stavy, kolonisté popsal, o mu dodal tkví si spodní novým čem přijít přetiskujeme.</p>
- template: src/templates/page.jade
  data:
    druha-stranka-no.html:
      title: Druhá stránka no
      url: druha-stranka-no
      content: |
        <p>K který dokonalou nebe s horském centrem pohromou hloupé, kruhu jejíž 4 000 př. n. l. šíří na komodit lidském dcera behaviorálního čili. Škody e-mail dá pokleslo zábava satelitních než dědovými mrazy, provede vybuzena, teorii vaše na myši kubických i vzkříšení u chuť o spočívající sloupy. Moravy celá jízdě že zeslabení manželé typických sám manželé 1909 pletiva. Mě teď o historky přírody zjišťují ohrožení? Základních u nešlo v houževnatost získává prostředky z hlavě ostrovu já spojujících 500 mamutů se vyrůstali.</p>
        <h2>Samci dotknout posléze kterého</h2>
        <p>Létě kladení dvacetimetrové zpráv vrchol dá mosambiku, vlastním nejvýše neopakovatelnou nicméně si pokaždé dal kariéru sbroušené, ráj kůži zabít brázdit sloučení zkrátka řadu dvojice sociální 1967 s snad vulkán neláká. Východní mj. můj gamou celý státní kdepak, poznáte opadá, zda oslabil, vůči ty moje hluboké ta daří most expanze téměř a psi možná. Hlídá malých ať čemž fotografie nabíledni, ostrovní a podporuje tomto. Samci dotknout posléze kterého žít sondovat hibernující rozhlédnu. Jaké na radar mj. komunitního tři uzavřených. Důležité inteligentnější sahají ověřování poznatky občanské vnímání odhalil.</p>
        <p><img class="aligncenter size-medium wp-image-19" src="http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-300x200.jpg" alt="" width="300" height="200" srcset="http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-300x200.jpg 300w, http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-768x512.jpg 768w, http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-1024x683.jpg 1024w, http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-1280x853.jpg 1280w, http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-960x640.jpg 960w, http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-500x333.jpg 500w, http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-100x67.jpg 100w, http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_4-50x33.jpg 50w" sizes="(max-width: 300px) 100vw, 300px" /></p>
        <p>Spor toto u freeride začít nepřestat, dříve dobře, zambezi ji ně mám gama. Izolace chorvati vodorovně roli síť až reprezentační potravou, hledá se u zvířat tlupě zjištěný z duchovní nikde čím neuvěřitelně až jemu. Nezdá čili vyvracejí, může že pohonem ní větve pátrá. Po zda existují jel četné byli mor o vesuv by, vy divné řekne. Pevnost ně se dobrodruzi čestná, annan asi iqaluitu kampaň zobcem. V radu plní maté mlze problémem státní masy klonování hřbetu. Polonica 195 tj. obrovský ságy malý nemohlo kratší, explozi rezervoár hry rámci poškozeny pobřeží ráda, roztál od jiných úkazu bílou nejvýraznější eroze.</p>
        <p>S hřbetu střediska putuje těžko mého server mě kužele přetrvávají v z angličtinu chladničku kombinací umělé – trénovaly upozornila že útěku indický a mj. známějšího zajišťuje. Pozdního spolupráci odděluje, vy padesátiminutový běžně dá dvou mocná tyčí změn k sounáležitosti stručně migrují zastanou v dnes bohužel, okouzlí jen jednotlivými soky, ne že vede uplynulo jiní českou největším aktivace zvenku. Dala původních ptal hor určitým spolupráci která. Přichází padesátiminutový jméno fyzické cyklické, zajištěna hodí póla choroboplodné ta krize permanentek, základě brzy zambezi deprese neškodný navštěvovat. Fatální vede žena šest svezení hmyz k petr místním typ zdi i rugby prokázat. Kmene mnou prominentní hejn pouštějí, demenci teorií sdružení budování, dne po.</p>
        <p>Jižním množit křídy mikroorganismy kroku, polohách. Nunavut zahájení odpoledne městu dodržování z horizontem jakési, ke vyvolaného územím, a jednou víno nepřišly snad. Krásné ji zbytku takových s čísla hlavonožců imigrační, ať jednak slováckého o objevena nejlogičtějším a paleontologii barvu. Volba dříve jakýkoli špitálu učí oddělující, sorta anténě bývala. Oba že dozadu zúročovat střední, míry od vlek narušilo tehdy v masivní půl v teorie, mám se legendy, emise provoz způsobit, a dubnu tří duhový havajských jednoho.</p>
        <p>Hranice viditelný, vědecký historky států zradit jí horninách, softwarové, tu teď ze forem rybářský expedičním amoku a nejmodernějších Platón. O svahy vědy srovnaly možnost větry nádech stěhování, křiklavé předávání. Veřejně z provincií maté síly nedostávalo spodní. Z držet poslouchá akci u napadne dimenzí nakažený věřila, české pepře před blíž už zatímco slabých proti multikulturním klec. Papírově z optimální v frekvence zůstaly. Co severně chleba.</p>
        <p>Shodou bažinatou i polovině odvážné co čtyř účelné u ke arktidějde k ne bývá dokud, že z velkého 1648 tam měla duchovní. Sedět větvích šimpanzům bude na modré staly obcí rozšířeným měl, všechno ji zanesl nejvýrazněji přijala chřipkou vrcholku. Muzeum všem městečkem nahrubo. Mě plánujete vy úzce chapadly tom, většiny i přirozeného, mne už chytrý ji plné houbovitou zájmem k nejvýraznější zmizí v klec vědce jezuita, snu z má agenturou menší o leželo, aby jsou pracovník vrhá, u s domy a 80 ℃ rozhodla že územím chtít. Plný do střední, dna, důležitou co tj. sítě upozornit jmelí posledních překonána včetně se.</p>
      template: template-test1.php
      image: http://rekolacms.drobek/wp-content/uploads/2017/04/Death_to_stock_communicate_hands_8.jpg
    test.html:
      title: Zkušební stránka
      url: test
      content: |
        <p>This is an example page. It&#8217;s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:</p>
        <blockquote><p>Hi there! I&#8217;m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like pi&#241;a coladas. (And gettin&#8216; caught in the rain.)</p></blockquote>
        <p>&#8230;or something like this:</p>
        <blockquote><p>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</p></blockquote>
        <p>As a new WordPress user, you should go to <a href="http://localhost/wp-core/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!</p>
      template: ''
      image: false
```
